### ISSUE TITLE
Power button does not work

### ISSUE THREAD

**Issue by coolguy129** [GloDroid/glodroid_manifest#88] opened 2020-09-23 18:41 UTC
after flashing image to emmc successfully, i have noticed that I am unable to put the phone into sleep mode. When i double tap the power button, it opens the camera and when I hold it down, it shows the shutdown prompt, but when i tap it, rather than going to sleep, it goes to the home screen. I also have tried to do the factory data reset.

**Comment by rsglobal** [comment] 2020-09-23 20:17
Duplicate of #83

**Closed** 2021-05-06 16:10 UTC
Labels: duplicate
