### ISSUE TITLE
Pinephone Wifi not connecting to encrypted SSID

### ISSUE THREAD

**Issue by dewitpj** [GloDroid/glodroid_manifest#33] opened 2020-07-08 09:00 UTC
Hi,

I have a SSID with a pretty long key - 26 chars to be exact :)

I could connect to this SSID using UBPORTS but in GloDriod it goes disabled. I am not sure what more debugging to send you, please ask :)

SSID is using WPA Personal, WPA2 Only - with CCMP encryption.

Thanks !

**Comment by dewitpj** [comment] 2020-07-08 21:36
Worth noting - WiFi works when connecting to an unencrypted SSID

**Comment by philnik777** [comment] 2020-07-25 19:17
I could not reproduce the problem. I used "123456789012345678901234567890". What version do you use? I used 0.3.0. Is it some combination of characters? It would be great if you could try that or just post the password if it is not important.

**Comment by philnik777** [comment] 2020-07-25 19:18
Did you use the same SSID? If not it may be that as well.

**Comment by dewitpj** [comment] 2020-07-25 19:23
> Did you use the same SSID? If not it may be that as well.

I created a new SSID....originally called...."Test"

It might be the encryption types - I will post those shortly

**Comment by dewitpj** [comment] 2020-07-25 19:26
![Screen Shot 2020-07-26 at 07 25 19](https://user-images.githubusercontent.com/17187660/88464738-46f3d500-cf11-11ea-8e81-c9550e1b1293.png)

Oh and yes, this was on 0.3.0 :)

**Comment by rsglobal** [comment] 2020-08-07 06:44
Please test if this issue is fixed:
https://github.com/GloDroid/glodroid_manifest/issues/58#issuecomment-670354906

**Comment by herbsmn** [comment] 2022-11-04 15:13
I was able to connect to an encrypted SSID on my PinePhone running v0.8.1. I suggest closing this issue.

**Closed** 2022-11-04 15:53 UTC
Labels: bug
