### ISSUE TITLE
Porting to Orange Pi Plus / Plus 2

### ISSUE THREAD

**Issue by vikitinho** [GloDroid/glodroid_manifest#15] opened 2020-04-14 19:40 UTC
I'm trying to port your project to run on an Orange Pi Plus / Plus 2 and thus contribute to more users.

I created a new device dir based on the plus2e configuration files, changed the dtb kernel to the respective one for this device (sun8i-h3-orangepi-plus.dtb), did the same for the uboot configuration.

After generating the sdcard.img, android starts, but I see the TV message "Android System: There's an internal problem with your device. Contact your manufacturer for details."

Attached ttyUSB log.

Is there anyone who can and wants to help me?
[minicom-09042020.txt](https://github.com/GloDroid/glodroid_manifest/files/4477362/minicom-09042020.txt)

Best Regards from Brazil

**Comment by rsglobal** [comment] 2020-04-15 08:29
Hello,

Is seems that your system have similar issue with opi3 and musb driver is configured to host mode only. The solution was to override this settings using device-tree overlay. Refer to https://github.com/GloDroid/glodroid_device/commit/a89844656b7343628b5892469b18ccc10e68c2a5 for more information.

**Comment by vikitinho** [comment] 2020-04-15 18:54
I tried to make the suggested change, but I get a new error ...

```
Loading Environment from EXT4... 
** Unable to use mmc 0:auto for loading the env **
In:    serial
Out:   serial
Err:   serial
Net:   phy interface7
eth0: ethernet@1c30000
starting USB...
No working controllers found
Autoboot in 1 seconds, press <Space> to stop
1871 bytes read in 1 ms (1.8 MiB/s)
## Executing script at 53000000
switch to partitions #0, OK
mmc0 is current device

MMC read: dev # 0, block # 8192, count 49152 ... 49152 blocks read: OK
failed on fdt_overlay_apply(): FDT_ERR_NOTFOUND
## Booting Android Image at 0x50008000 ...
Kernel load addr 0x40088000 size 7207 KiB
Kernel command line: androidboot.hardware=plus buildvariant=userdebug
RAM disk load addr 0x43300000 size 6122 KiB
   Loading Kernel Image
   Loading Ramdisk to 49a05000, end 49fff415 ... OK

Starting kernel ...


Error: invalid dtb and unrecognized/unsupported machine ID
  r1=0x00000000, r2=0x40000100
  r2[]=05 00 00 00 01 00 41 54 00 00 00 00 00 00 00 00
Available machine support:

ID (hex)        NAME
ffffffff        Generic DT based system
ffffffff        Allwinner suniv Family
ffffffff        Allwinner sun9i Family
ffffffff        Allwinner A83t board
ffffffff        Allwinner sun8i Family
ffffffff        Allwinner sun7i (A20) Family
ffffffff        Allwinner sun6i (A31) Family
ffffffff        Allwinner sun4i/sun5i Families

Please check your kernel config and/or bootloader.
```

'll do more detailed tests and I'll be back when I have more information. I appreciate the support.

**Comment by rsglobal** [comment] 2020-04-16 07:16
Could you share you changes?

**Comment by hostkit** [comment] 2020-04-26 16:40
> Hello,
> 
> Is seems that your system have similar issue with opi3 and musb driver is configured to host mode only. The solution was to override this settings using device-tree overlay. Refer to [GloDroid/glodroid_device@a898446](https://github.com/GloDroid/glodroid_device/commit/a89844656b7343628b5892469b18ccc10e68c2a5) for more information.
> 
> At least you should be able to run `adb shell`, use `fastbootd`, etc. after that.

Sometimes plus2e Android System: There's an internal problem with your device. Contact your manufacturer for details.

**Comment by BigJacek** [comment] 2020-06-01 21:11
Hello,
Clould you pls. extend the project to support Orange Pi Plus / Plus 2?
Best regards,
Jacek

**Comment by rsglobal** [comment] 2020-06-02 07:12
Hello Jacek,

Thank you for your request. 
Currently our team does not have such boards.
I will ask Xunlong to sponsor our project with boards, and will start working on new devices as soon as they arrive.

**Comment by BigJacek** [comment] 2020-06-02 07:59
Hello,
Thank you very much for your quick answer. 
I keep my fingers crossed for a quick delivery of the device from your sponsor and I hope that Orange Pi Plus / Plus 2 will soon be supported.
Best regards,
Jacek

**Comment by BigJacek** [comment] 2020-06-05 16:54
Btw. Can I help in some way?
I'm new here, but if there's anything I can do, I'd love to join in.

**Comment by rsglobal** [comment] 2020-06-05 19:09
Hello Jacek,

Yes you can.
Enabling basic functionality for plus / plus2 is trivial task, but it require testing on real hardware.
You can build it yourself or I can provide images for testing.

Regards,
Roman

**Comment by BigJacek** [comment] 2020-06-05 19:55
OK.
So I have one piece of Orange Pi Plus2 H3 and I would like to test something.
So let's start with an image for testing.
After all, I would like to be able to build the image myself.

**Comment by BigJacek** [comment] 2020-06-08 15:08
Hello Roman,
Can you provide images for testing?
Regards,
Jacek

**Comment by rsglobal** [comment] 2020-06-08 21:24
Hi Jacek,
Just give me a couple of days.
Currently I am working on rpi4 integration. I will start working on this issue soon.
Regards,
Roman

**Comment by BigJacek** [comment] 2020-06-08 22:27
Roman,
Sure, no problem.
In the meantime I'm trying  to build GloDroid repo on my PC.
We're in contact.
Jacek

**Comment by BigJacek** [comment] 2020-06-11 10:10
Hello Roman,
I'm trying to build GloDroid repo on my PC based on description in the web.
There are some problems and finally there are unable to sync repo.
Pls. see errors below:
error: build/blueprint/: platform/build/blueprint checkout 675d72d5f3b3200f6dcc174d8bda00c227abd36c 
error: external/autotest/: platform/external/autotest checkout 0c09d81ab60ad4e45c0dacb9f4ddb989f16e20e6 
error: external/kmod/: platform/external/kmod checkout e6417e44d57fcdfcce1eb96f9443dca49bdf91ea 
error: external/libunwind/: platform/external/libunwind checkout 7da670a13886265d84bd5d78475a6329c038df10 
and finally:
error: unable to create file tests/P_str_escape/str\\escape.rs: Zły argumentdating files:  57% (491/856)
error: Cannot checkout platform/frameworks/compile/slang: GitError: Cannot initialize work tree for platform/frameworks/compile/slang
error.GitError: Cannot initialize work tree for platform/frameworks/compile/slang

Is there any solution for that?
Jacek

**Comment by rsglobal** [comment] 2020-06-11 14:36
Hello Jacek,

Could you check disk space usage? 
`df -h`

**Comment by BigJacek** [comment] 2020-06-11 17:12
Hello,
Disk usage:
System plików  rozm. użyte dost. %uż. zamont. na
udev            1,9G     0  1,9G   0% /dev
tmpfs           391M  1,9M  390M   1% /run
/dev/sda5        20G   14G  4,6G  75% /
tmpfs           2,0G     0  2,0G   0% /dev/shm
tmpfs           5,0M  4,0K  5,0M   1% /run/lock
tmpfs           2,0G     0  2,0G   0% /sys/fs/cgroup
/dev/loop0       55M   55M     0 100% /snap/core18/1705
/dev/loop1       55M   55M     0 100% /snap/core18/1754
/dev/loop3       50M   50M     0 100% /snap/snap-store/433
/dev/loop2      256M  256M     0 100% /snap/gnome-3-34-1804/36
/dev/loop4       63M   63M     0 100% /snap/gtk-common-themes/1506
/dev/loop5       31M   31M     0 100% /snap/snapd/7777
/dev/loop6       28M   28M     0 100% /snap/snapd/7264
/dev/loop7       50M   50M     0 100% /snap/snap-store/454
/dev/loop8      241M  241M     0 100% /snap/gnome-3-34-1804/24
/dev/sda1       511M  4,0K  511M   1% /boot/efi
vmhgfs-fuse     238G  186G   53G  78% /mnt/hgfs
tmpfs           391M   20K  391M   1% /run/user/1000
/dev/sdb1       299G   69G  230G  23% /media/adminek/Citrix

repo is on resource sdb1

Regards,
Jacek

**Comment by rsglobal** [comment] 2020-06-12 04:57
I've had similar issue.
In my case repository in `.repo/projects/ `directory was broken.
Try to delete repositories listed in error log you've attached from .repo/projects/ and run `repo sync` again.

**Comment by BigJacek** [comment] 2020-06-12 08:13
Yes. I thought about it too, and I did, but still no luck.
I removed the whole repo and I'm starting over.

**Comment by BigJacek** [comment] 2020-06-12 18:21
The fourth time after each repo removal, the synchronisation was finally completed.

**Comment by BigJacek** [comment] 2020-06-12 19:34
Hello,
I wanted to biuld image for sdcard (for testing purposes) but everytime I've got an error:
$ make sdcard
============================================
PLATFORM_VERSION_CODENAME=REL
PLATFORM_VERSION=10
TARGET_PRODUCT=opi_pc
TARGET_BUILD_VARIANT=userdebug
TARGET_BUILD_TYPE=release
TARGET_ARCH=arm
TARGET_ARCH_VARIANT=armv7-a-neon
TARGET_CPU_VARIANT=generic
HOST_ARCH=x86_64
HOST_2ND_ARCH=x86
HOST_OS=linux
HOST_OS_EXTRA=Linux-5.4.0-37-generic-x86_64-Ubuntu-20.04-LTS
HOST_CROSS_OS=windows
HOST_CROSS_ARCH=x86
HOST_CROSS_2ND_ARCH=x86_64
HOST_BUILD_TYPE=release
BUILD_ID=QQ2A.200305.004.A1
OUT_DIR=out
============================================
[100% 47/47] out/soong/.bootstrap/bin/soong_build out/soong/build.ninja
FAILED: out/soong/build.ninja
out/soong/.bootstrap/bin/soong_build -t -l out/.module_paths/Android.bp.list -b out/soong -n out -d out/soong/build.ninja.d -globFile out/soong/.bootstrap/build-globs.ninja -o out/soong/build.ninja Android.bp
Killed
21:26:56 soong bootstrap failed with: exit status 1
ninja: build stopped: subcommand failed.
#### failed to build some targets (05:19 (mm:ss)) ####
What could be wrong?

Jacek

**Comment by BigJacek** [comment] 2020-06-12 19:40
Hello,
I wanted to biuld image for sdcard (for testing purposes) but everytime I've got an error:
$ make sdcard
PLATFORM_VERSION_CODENAME=REL
PLATFORM_VERSION=10
TARGET_PRODUCT=opi_pc
TARGET_BUILD_VARIANT=userdebug
TARGET_BUILD_TYPE=release
TARGET_ARCH=arm
TARGET_ARCH_VARIANT=armv7-a-neon
TARGET_CPU_VARIANT=generic
HOST_ARCH=x86_64
HOST_2ND_ARCH=x86
HOST_OS=linux
HOST_OS_EXTRA=Linux-5.4.0-37-generic-x86_64-Ubuntu-20.04-LTS
HOST_CROSS_OS=windows
HOST_CROSS_ARCH=x86
HOST_CROSS_2ND_ARCH=x86_64
HOST_BUILD_TYPE=release
BUILD_ID=QQ2A.200305.004.A1
OUT_DIR=out
[100% 47/47] out/soong/.bootstrap/bin/soong_build out/soong/build.ninja
FAILED: out/soong/build.ninja
out/soong/.bootstrap/bin/soong_build -t -l out/.module_paths/Android.bp.list -b out/soong -n out -d out/soong/build.ninja.d -globFile out/soong/.bootstrap/build-globs.ninja -o out/soong/build.ninja Android.bp
Killed
21:26:56 soong bootstrap failed with: exit status 1
ninja: build stopped: subcommand failed.

failed to build some targets (05:19 (mm:ss))
What could be wrong?

Jacek

**Comment by rsglobal** [comment] 2020-06-12 19:46
You are out of memory.
Close chrome and other apps and try again. Also you should have at least 16gb of RAM.
Doing make -j1 sdcard could also help, but on final building stages.

**Comment by BigJacek** [comment] 2020-06-12 19:56
Ah, ok.
I'm working on VM so I just can forget about this.

**Comment by hostkit** [comment] 2020-06-13 08:32
> You are out of memory.
> Close chrome and other apps and try again. Also you should have at least 16gb of RAM.
> Doing make -j1 sdcard could also help, but on final building stages.

Higher specific unable build it self

**Comment by BigJacek** [comment] 2020-06-13 10:52
Lack of RAM.
I won't go through with it now.

**Comment by BigJacek** [comment] 2020-06-14 18:43
Hello Roman,
Can you provide some images for testing (when you have a moment, of course)?
Regards,
Jacek

**Comment by BigJacek** [comment] 2020-06-14 18:45
Unfortunately, that's all I can do right now.

**Comment by rsglobal** [comment] 2020-06-18 10:15
Hello Jacek,

I've build images for you. I expect some issues since kernel is mainline without Google patches. But UI should start.
https://drive.google.com/file/d/1gJCYklek2yMQDqpokeZo2pl9ILPRUtVK/view?usp=sharing

**Comment by BigJacek** [comment] 2020-06-18 11:24
Hello Roman,
I'm starting to work on this.
JaS

**Comment by BigJacek** [comment] 2020-06-18 19:59
Roman,
I've got a problem.
In recovery mode device is not listed by command "adb devices" (every time I get a message: error: no devices/emulators found).
However device is mapped as removables device (Onda MT65xx Preloader).
I'm using Ubuntu 20.04 LTS.
Regards,
Jacek

**Comment by vikitinho** [comment] 2020-06-18 20:10
Hi Roman,  

I did the same test and got the same error.

Attached ttyUSB log.

[minicom-18062020.log](https://github.com/GloDroid/glodroid_manifest/files/4800956/minicon-18062020.log)

**Comment by rsglobal** [comment] 2020-06-18 20:11
In case you are in fastbootd mode, adb won't work.

I'll look into it tomorrow.

**Comment by BigJacek** [comment] 2020-06-18 20:38
I did this also but no reaction on Pi Plus 2 side. (not reload/reboot)

**Comment by BigJacek** [comment] 2020-06-18 20:41
< waiting for any device >

and nothing more...

**Comment by rsglobal** [comment] 2020-06-19 05:03
Jacek,

Unfortunately I can see no usb_otg node in orange pi plus device tree in both u-boot and kernel project.
You can try to copy-paste it from opi pc, recompile kernel and try again.

**Comment by rsglobal** [comment] 2020-06-19 07:03
Plus2 board have no schematic publicly available.
To enable USB I should specify to which H3 SOC pin USB-ID OTG contact is routed.

Can anybody who have broken board, remove SOC and probe ID pin using multimeter?

**Comment by BigJacek** [comment] 2020-06-19 08:22
I dont know if it will be usefull/helpful but there is orangepi-plus-h3-v1_1_schematic available (https://pan.baidu.com/s/1bnppzv5).
As far as I can see, the firmware is the same for both versions, so maybe the architecture is similar.

**Comment by rsglobal** [comment] 2020-06-19 09:22
Thank you for the link.
Lets assume plus and plus2 have same pcb layout.
From the circuit diagram:
```
PG12 - USB0_IDDET
PL2 - USB0_DRVVBUS
```

**Comment by BigJacek** [comment] 2020-06-19 09:30
ok.

**Comment by BigJacek** [comment] 2020-06-19 09:30
I was just about to write it.
;)

**Comment by rsglobal** [comment] 2020-06-19 12:26
@BigJacek , @vikitinho 
I've updated images, could you test it please?
https://drive.google.com/file/d/1AnSOOrhmPjvxW9sMMOE_NzwxXdhIR50t/view?usp=sharing

**Comment by BigJacek** [comment] 2020-06-19 13:29
Roman,
I'm starting to work on this.
JaS

**Comment by BigJacek** [comment] 2020-06-19 14:22
Brief summary:
I flashed Android on sdcard using a new deploy-sd.img.
Inserted recovery sdcard into the OPP2 board.
Connected microusb cable to OTG connector and my PC.
Powered-up the board.
After a short while the system (Windows 10) detected a new device in the Universal Serial Bus Controllers section (Unknown USB device (port reset failed).
 Since I'm working on Ubuntu using VM I can't remap this device on VMware (just can't see it). 
The difference is that the device is already in the system.
I tried also fastboot reboot-recovery in Windows but still  < waiting for any device > only and nothing more...

**Comment by BigJacek** [comment] 2020-06-19 14:23
maybe @vikitinho will have more luck

**Comment by BigJacek** [comment] 2020-06-19 14:28
I tried to install various drivers for this device in Windows but without success (even in unsigned driver installation mode).

**Comment by vikitinho** [comment] 2020-06-19 14:38
I'm starting to work on this.

I return with information in a few hours

**Comment by vikitinho** [comment] 2020-06-19 15:44
Boot OK:

[minicom-19062020.log](https://github.com/GloDroid/glodroid_manifest/files/4805481/minicom-19062020.log)

Fastboot nOK

I believe there is a problem with the driver on ubuntu, you will analyze and analyze information later.

ubuntu@ubuntu:~$ dmesg -w
[ 3055.245373] usb usb3-port1: Cannot enable. Maybe the USB cable is bad?
[ 3056.213471] usb usb3-port1: Cannot enable. Maybe the USB cable is bad?
[ 3056.213557] usb usb3-port1: attempt power cycle
[ 3057.497439] usb usb3-port1: Cannot enable. Maybe the USB cable is bad?
[ 3058.465445] usb usb3-port1: Cannot enable. Maybe the USB cable is bad?
[ 3058.465531] usb usb3-port1: unable to enumerate USB device

**Comment by rsglobal** [comment] 2020-06-19 17:16
@vikitinho @BigJacek ,

Thanks for testing. The problem with USB enumeration is from device side. Lets make 2 more attempts with different DTS node enabled.

**Comment by rsglobal** [comment] 2020-06-19 17:19
Attempt #3: https://drive.google.com/file/d/1w5fIzY07AYOdB8IrwH5xJ9G9npy6C9jE/view?usp=sharing

**Comment by BigJacek** [comment] 2020-06-19 18:02
ok. 
I'm starting to work on this.

**Comment by BigJacek** [comment] 2020-06-19 18:20
Brief summary:
Windows 10  detected a new device in the Universal Serial Bus Controllers section (Unknown USB device (port reset failed).
new:
at now it is possible to remap this device on VMware and is visible on ubuntu as "google usb download gadget".
I tried "fastboot reboot-recovery" in Windows and Ubuntu also but still < waiting for any device > only and nothing more...

**Comment by BigJacek** [comment] 2020-06-19 18:22
"fastboot device" doesn't recognize any device(s)

**Comment by vikitinho** [comment] 2020-06-19 18:39
Hi!

Fastboot not work.

[minicom-19062020-1.log](https://github.com/GloDroid/glodroid_manifest/files/4806240/minicom-19062020-1.log)

ubuntu@ubuntu:~$ dmesg
[13859.711875] usb 3-4: new high-speed USB device number 60 using xhci_hcd
[13859.860176] usb 3-4: New USB device found, idVendor=18d1, idProduct=4ee0
[13859.860180] usb 3-4: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[13859.860183] usb 3-4: Product: USB download gadget
[13859.860186] usb 3-4: Manufacturer: Allwinner Technology
[13859.860189] usb 3-4: SerialNumber: 02c000819bd7bda4
ubuntu@ubuntu:~$ ./fastboot reboot
< waiting for any device >

**Comment by rsglobal** [comment] 2020-06-19 18:40
#4: https://drive.google.com/file/d/1DjiIPRoVMcGxxN0JPPt_Ly2Wo_xcxSko/view?usp=sharing

**Comment by rsglobal** [comment] 2020-06-19 18:42
@vikitinho , 

It seems that Number 3 works for you.
Try ```sudo ./fastboot reboot```

**Comment by BigJacek** [comment] 2020-06-19 18:46
@rsglobal 
It seems that Number 3 works similar to my as "google usb download gadget".
I tried ./fastboot reboot in sudo mode but < waiting for any device > only

**Comment by BigJacek** [comment] 2020-06-19 18:47
I'm starting to work on attempt 4

**Comment by vikitinho** [comment] 2020-06-19 18:51
```
ubuntu@ubuntu:~$ sudo ./fastboot reboot
Rebooting                                          OKAY [  0.000s]
Finished. Total time: 0.552s
```

I'll install and come back with more information

**Comment by BigJacek** [comment] 2020-06-19 19:08
ok 
probably there is a problem to remap this device on VMware -> however it is visible as "google usb download gadget" but not directly on ubuntu (VMware indicator light is probably cheating on something).

@vikitinho in you the only hope

**Comment by BigJacek** [comment] 2020-06-19 19:09
I'll keep track of it. Maybe something else will enlighten me.

**Comment by vikitinho** [comment] 2020-06-19 19:23
After (fastboot erase misc) waiting...

[minicom-19062020-4.log](https://github.com/GloDroid/glodroid_manifest/files/4806388/minicom-19062020-4.log)

```
ubuntu@ubuntu:~$ sudo ./flash-sd.sh 
+ ./fastboot flash gpt deploy-gpt.img
Sending 'gpt' (128 KB)                             OKAY [  0.015s]
Writing 'gpt'                                      OKAY [  0.242s]
Finished. Total time: 0.267s
+ ./fastboot flash bootloader bootloader-sd.img
Sending 'bootloader' (1920 KB)                     OKAY [  0.144s]
Writing 'bootloader'                               OKAY [  0.101s]
Finished. Total time: 0.254s
+ ./fastboot flash uboot-env env.img
Sending 'uboot-env' (256 KB)                       OKAY [  0.023s]
Writing 'uboot-env'                                OKAY [  0.028s]
Finished. Total time: 0.059s
+ ./fastboot reboot
Rebooting                                          OKAY [  0.000s]
Finished. Total time: 0.601s
+ set +x
+ ./fastboot oem format
< waiting for any device >
                                                   OKAY [  1.273s]
Finished. Total time: 1.274s
+ ./fastboot flash bootloader bootloader-sd.img
Sending 'bootloader' (1920 KB)                     OKAY [  0.143s]
Writing 'bootloader'                               OKAY [  0.100s]
Finished. Total time: 0.254s
+ ./fastboot flash uboot-env env.img
Sending 'uboot-env' (256 KB)                       OKAY [  0.023s]
Writing 'uboot-env'                                OKAY [  0.035s]
Finished. Total time: 0.068s
+ ./fastboot flash recovery_boot boot.img
Sending 'recovery_boot' (24576 KB)                 OKAY [  1.763s]
Writing 'recovery_boot'                            OKAY [  1.992s]
Finished. Total time: 3.783s
+ ./fastboot erase misc
Erasing 'misc'                                     OKAY [  0.014s]
Finished. Total time: 0.033s
+ ./fastboot reboot-fastboot
Rebooting into fastboot                            OKAY [  0.010s]
< waiting for any device >
```

**Comment by rsglobal** [comment] 2020-06-19 19:41
Thanks guys, good results.
I haven't tested this kernel with sunxi boards yet, so maybe some issues caused by v5.7 migration. I'll take a look next week.

@vikitinho , I'll push my changes into next branch, so you can sync it if you want to build yourself.

**Comment by rsglobal** [comment] 2020-06-19 19:43
@BigJacek , can you run `sudo dmesg -w` on your virtual machine and see if any logs appears when you plug OTG?

**Comment by vikitinho** [comment] 2020-06-19 19:46
> Thanks guys, good results.
> I haven't tested this kernel with sunxi boards yet, so maybe some issues caused by v5.7 migration. I'll take a look next week.
> 
> @vikitinho , I'll push my changes into next branch, so you can sync it if you want to build yourself.

Thank you! I am available to do the tests you need!

**Comment by rsglobal** [comment] 2020-06-19 20:36
@vikitinho ,
I switched kernel back to v0.2.0 and added missing dts nodes:
v5: https://drive.google.com/file/d/1PrkMEyTb1EmdrFTpwn8qQyV7KkVZLmCA/view?usp=sharing

**Comment by vikitinho** [comment] 2020-06-19 21:36
I tested it, android started with the message:

"Android System: There's an internal problem with your device. Contact your manufacturer for details."

[minicom-19062020-5.log](https://github.com/GloDroid/glodroid_manifest/files/4806766/minicom-19062020-5.log)

The installation was successful:

```
ubuntu@ubuntu:~$ sudo ./flash-sd.sh 
+ ./fastboot flash gpt deploy-gpt.img
Sending 'gpt' (128 KB)                             OKAY [  0.016s]
Writing 'gpt'                                      OKAY [  0.643s]
Finished. Total time: 0.668s
+ ./fastboot flash bootloader bootloader-sd.img
Sending 'bootloader' (1920 KB)                     OKAY [  0.146s]
Writing 'bootloader'                               OKAY [  0.107s]
Finished. Total time: 0.262s
+ ./fastboot flash uboot-env env.img
Sending 'uboot-env' (256 KB)                       OKAY [  0.025s]
Writing 'uboot-env'                                OKAY [  0.029s]
Finished. Total time: 0.062s
+ ./fastboot reboot
Rebooting                                          OKAY [  0.000s]
Finished. Total time: 0.602s
+ set +x
+ ./fastboot oem format
< waiting for any device >
                                                   OKAY [  0.014s]
Finished. Total time: 0.014s
+ ./fastboot flash bootloader bootloader-sd.img
Sending 'bootloader' (1920 KB)                     OKAY [  0.139s]
Writing 'bootloader'                               OKAY [  0.106s]
Finished. Total time: 0.256s
+ ./fastboot flash uboot-env env.img
Sending 'uboot-env' (256 KB)                       OKAY [  0.025s]
Writing 'uboot-env'                                OKAY [  0.030s]
Finished. Total time: 0.065s
+ ./fastboot flash recovery_boot boot.img
Sending 'recovery_boot' (24576 KB)                 OKAY [  1.766s]
Writing 'recovery_boot'                            OKAY [  1.784s]
Finished. Total time: 3.577s
+ ./fastboot erase misc
Erasing 'misc'                                     OKAY [  0.014s]
Finished. Total time: 0.031s
+ ./fastboot reboot-fastboot
Rebooting into fastboot                            OKAY [  0.010s]
< waiting for any device >
Finished. Total time: 13.695s
+ ./fastboot flash boot_a boot.img
Sending 'boot_a' (24576 KB)                        OKAY [  1.863s]
Writing 'boot_a'                                   OKAY [  1.995s]
Finished. Total time: 3.916s
+ ./fastboot flash dtbo_a boot_dtbo.img
Sending 'dtbo_a' (28 KB)                           OKAY [  0.023s]
Writing 'dtbo_a'                                   OKAY [  0.047s]
Finished. Total time: 0.075s
+ ./fastboot flash super super.img
Invalid sparse file format at header magic
Sending sparse 'super' 1/2 (520320 KB)             OKAY [ 40.128s]
Writing 'super'                                    OKAY [ 42.624s]
Sending sparse 'super' 2/2 (241064 KB)             OKAY [ 18.702s]
Writing 'super'                                    OKAY [ 57.969s]
Finished. Total time: 160.360s
+ ./fastboot format:ext4 metadata
Warning: metadata type is raw, but ext4 was requested for formatting.
mke2fs 1.44.4 (18-Aug-2018)
Creating filesystem with 4096 4k blocks and 4096 inodes

Allocating group tables: done                            
Writing inode tables: done                            
Creating journal (1024 blocks): done
Writing superblocks and filesystem accounting information: done

Sending 'metadata' (52 KB)                         OKAY [  0.010s]
Writing 'metadata'                                 OKAY [  0.490s]
Finished. Total time: 0.548s
+ ./fastboot format:ext4 userdata
Warning: userdata type is raw, but ext4 was requested for formatting.
mke2fs 1.44.4 (18-Aug-2018)
Creating filesystem with 7428859 4k blocks and 1859584 inodes
Filesystem UUID: 94847b40-6fdb-4aa4-9d16-947de37d37f8
Superblock backups stored on blocks: 
	32768, 98304, 163840, 229376, 294912, 819200, 884736, 1605632, 2654208, 
	4096000

Allocating group tables: done                            
Writing inode tables: done                            
Creating journal (32768 blocks): done
Writing superblocks and filesystem accounting information: done   

Sending 'userdata' (4420 KB)                       OKAY [  0.342s]
Writing 'userdata'                                 OKAY [  2.187s]
Finished. Total time: 2.603s
+ ./fastboot reboot
Rebooting                                          OKAY [  0.000s]
Finished. Total time: 0.050s
ubuntu@ubuntu:~$ 
```
Even with the error message, the abd recognizes the card, is there a command that I can run to debug?

```
ubuntu@ubuntu:~$ sudo ./adb devices
List of devices attached
02c000819bd7bda4	no permissions (user in plugdev group; are your udev rules wrong?); see [http://developer.android.com/tools/device.html]
```

**Comment by rsglobal** [comment] 2020-06-20 05:06
@vikitinho ,

You have to use sudo because you haven't corresponding udev rules instaled.

As stated at https://developer.android.com/studio/run/device#setting-up:

Ubuntu Linux: Use apt-get install to install the adb package. This gives you a community-maintained default set of udev rules for all Android devices.

So try `sudo apt install adb`

**Comment by BigJacek** [comment] 2020-06-20 05:20
> @BigJacek , can you run `sudo dmesg -w` on your virtual machine and see if any logs appears when you plug OTG?

I'll do the investigation later this weekend.

**Comment by rsglobal** [comment] 2020-06-20 05:33
```
"Android System: There's an internal problem with your device. Contact your manufacturer for details."
```
It is known issue on all opi devices. But I still do not know what is the reason.
@vikitinho ,
Could you also try to flash eMMC?

**Comment by BigJacek** [comment] 2020-06-20 17:36
In case of  attempt 3 I have the same experience working with adb/fastboot on Windows.
After flashed Android on sdcard using a new deploy-sd.img device is visible by flashboot.
Finally when I call fastboot reboot or reboot-bootloader (part of the script) device start to be unavailable.

**Comment by BigJacek** [comment] 2020-06-20 17:50
to be detailed:
fastboot oem format
fastboot flash bootloader      bootloader-sd.img
fastboot flash uboot-env       env.img
fastboot flash recovery_boot   boot.img
fastboot erase misc

fastboot reboot
...and nothing device is unavailable/unvisible in windows

**Comment by rsglobal** [comment] 2020-06-20 21:10
v3 has some bug in the kernel.
Try v5 instead: https://github.com/GloDroid/glodroid_manifest/issues/15#issuecomment-646851313

**Comment by BigJacek** [comment] 2020-06-21 21:29
Brief summary:
I installed the lastest version of Xubuntu on my oooold PC.
For testing purposes I used attempt 5 as you posted.
Results:
- Android system is up-and-running.
- video mode FullHD
- after desktop is displayed the message appears:
     Android System
     There's an internal problem with your device. Contact your manufacturer for details.
- lack of wifi and google play (I can only use wifi)
- keyboard and mouse work well
- sound works well
- languages available and switchable
- device model: opi_plus2

**Comment by BigJacek** [comment] 2020-06-21 21:38
my next step - try to flash eMMC

**Comment by BigJacek** [comment] 2020-06-21 21:42
I will also try to do something with the network so that it is available through the Ethernet socket.

**Comment by rsglobal** [comment] 2020-06-22 00:06
Please check if wifi works on v6:
https://drive.google.com/file/d/1pwpRbT5QhZ7n0fxbHYJc724jQVHM-DFy/view?usp=sharing

**Comment by BigJacek** [comment] 2020-06-22 07:11
Hello Roman,
Checked and  wifi works on v6.
By the way: is it possible to add support for USB Bluetooth devices?
I also tried flash eMMC but unfortunately there was a problem:
adminek@ESPRIMO-Q5030:~/images$ sudo ./fastboot devices
02c00081a5d66c7f	fastboot
adminek@ESPRIMO-Q5030:~/images$ sudo ./flash-emmc.sh
+ ./fastboot flash gpt deploy-gpt.img
Sending 'gpt' (128 KB)                             OKAY [  0.015s]
Writing 'gpt'                                      OKAY [  0.014s]
Finished. Total time: 0.030s
+ ./fastboot flash bootloader bootloader-emmc.img
Sending 'bootloader' (1920 KB)                     OKAY [  0.133s]
Writing 'bootloader'                               FAILED (remote: 'cannot find partition')
fastboot: error: Command failed
adminek@ESPRIMO-Q5030:~/images$
Regards,
JaS

**Comment by rsglobal** [comment] 2020-06-22 08:26
Hello Jacek,

Thank you for testing. Regarding eMMC, please ensure you are booting from `deploy-sd-for-emmc.img`, not a `deploy-sd.img`

**Comment by BigJacek** [comment] 2020-06-22 10:37
Brief summary:
Flashing eMMC work well. It was a problem with partition on my SD card (when I fixed it the android just started up).
Results:
- Android system is up-and-running.
- video mode FullHD
-after desktop is displayed the message appears:
    Android System
    There's an internal problem with your device. Contact your manufacturer for details.
- wifi works well
- keyboard and mouse work well
- sound works well
- languages available and switchable
- F-Droid tool does not work properly (although it starts but nothing works - it does not search for applications, it does not load groups).
The whole system works slowly and quite often individual functions get stuck.
I was able to run some videos from youtube (in the build-in browser) and it works quite well at 480p (higher resolutions stutter quite strongly).

**Comment by BigJacek** [comment] 2020-06-22 10:43
Ah, one more thing: I don't know why, but it often happens that the system does not boot (remains on the android logo). Turning the power off and on again makes the system load correctly again. (sometimes you have to do it twice)

**Comment by rsglobal** [comment] 2020-06-22 12:35
> Ah, one more thing: I don't know why, but it often happens that the system does not boot (remains on the android logo). Turning the power off and on again makes the system load correctly again. (sometimes you have to do it twice)

Could you catch this moment and save output of `$ adb shell logcat` and `$ adb shell dmesg`?

**Comment by rsglobal** [comment] 2020-06-23 10:44
Support for Orange PI Plus 2 is available in next branch and will be included into the next release.

**Closed by rsglobal** 2020-06-23 10:44 UTC

**Comment by BigJacek** [comment] 2020-06-23 13:19
Hello Roman,
I'm quite busy now but I remember about logs.
JaS

**Comment by BigJacek** [comment] 2020-06-28 07:08
Hello,
As promised, I'm sending some new information.
So I decided to do the whole installation to eMMC again (step by step).
Currently, after a few reboots, nothing is hanging / stopping at Android startup.
Unfortunately, as I wrote before, the system works quite slowly and often freezes but as such it works.
Regards,
JaS
