### ISSUE TITLE
Pinephone hardware acceleration

### ISSUE THREAD

**Issue by squidink7** [GloDroid/glodroid_manifest#175] opened 2021-12-15 09:05 UTC
When watching video on manjaro KDE mobile through the browser it can easily play back at a smooth near 60fps at 720p, however attempting to do the same thing on GloDroid 0.7.0 yields a far lower frame rate and heats up the device to a great extent. Is this due to some hardware acceleration that's missing here? or is it just the nature of android when compared to vanilla Linux. Some animations also seem to lag a little when theres apps open in the background, but I'm not sure if it's the same issue.

**Comment by rsglobal** [comment] 2021-12-16 10:15
Duplicate of #152 . 

Currently only software codecs are supported.
There is a way to integrate stateful codecs support which we will do for rpi4 near future, but allwinner has only  stateless codec APIs which require a lot of work to enable on mainline Android.

**Closed by rsglobal** 2021-12-16 10:15 UTC
